### PR TITLE
Made further improvements on architechture

### PR DESCRIPTION
**Pull request by kl3jvi**
Added repository module di and database di, also made get favorites from database as flow

### CODE REVIEW

**Comment by kl3jvi** [comment]
By mistake

**Comment by fakeyatogod** [comment]
> By mistake

I can cherry-pick it perhaps.?

**Comment by kl3jvi** [comment]
Sure go ahead

**Comment by kl3jvi** [comment]
Sure go ahead

**Comment by fakeyatogod** [comment]
Done with a65935b5b029d8d1d7ab53b17fb2bcf4035cc115

**Pull request closed without merging**
